### ISSUE TITLE
Changes to Adapter abstracts and virtuals

### ISSUE THREAD

**Issue by ThatRendle** [craiggwilson/Simple.Data.MongoDB#4]
Hi Craig,

Our discussion about what gets handled in the Core layer, and how in some cases it's biased towards the Ado adapter, caused me to go back and think about the basic methods and how they're implemented. The main change is that I've stopped trying to create Criteria for the Update(object) method, and I just pass the tablename and the data directly to the adapter so it can perform the update in its own way. The GetKeyFields method has, therefore, gone. That "Get" prefix was a clear indication that this was a classic case of asking instead of telling, really, but I've fixed it now.

Also, some of the methods have become virtual instead of abstract, and provide default implementations, but can be overridden where you can optimize the operations, e.g. bulk queries or bulk inserts.

I've also added proper doc comments on all the Adapter methods.

I'll be pushing this to NuGet as 0.9, since it's a change to the external API, but I wanted to give you a heads-up.

Cheers,
Mark

**Comment by craiggwilson** [comment]
You are awesome. I'll jump on it this weekend.

Sent from my Windows Phone From: markrendle
Sent: Wednesday, August 10, 2011 7:25 AM
To: craiggwilson@gmail.com
Subject: [Simple.Data.MongoDB] Changes to Adapter abstracts and
virtuals (#4)
Hi Craig,

Our discussion about what gets handled in the Core layer, and how in
some cases it's biased towards the Ado adapter, caused me to go back
and think about the basic methods and how they're implemented. The
main change is that I've stopped trying to create Criteria for the
Update(object) method, and I just pass the tablename and the data
directly to the adapter so it can perform the update in its own way.
The GetKeyFields method has, therefore, gone. That "Get" prefix was a
clear indication that this was a classic case of asking instead of
telling, really, but I've fixed it now.

Also, some of the methods have become virtual instead of abstract, and
provide default implementations, but can be overridden where you can
optimize the operations, e.g. bulk queries or bulk inserts.

I've also added proper doc comments on all the Adapter methods.

I'll be pushing this to NuGet as 0.9, since it's a change to the
external API, but I wanted to give you a heads-up.

Cheers,
Mark

## 

Reply to this email directly or view it on GitHub:
https://github.com/craiggwilson/Simple.Data.MongoDB/issues/4
